services:
  jupyter-without-kaggledatasets:
    image: optiver-trading/without-kaggledatasets
    build:
      context: .
      args:
        ENABLE_KAGGLE_DATASETS: "false"
    ports:
      - "${EXTERNAL_PORT:-8888}:8888"
    volumes:
      - ./:/app
    env_file:
      - ./jupyter-config/.env
    restart: unless-stopped
    profiles: ["local-default"]

  jupyter-with-kaggledatasets:
    image: optiver-trading/with-kaggledatasets
    build:
      context: .
      args:
        ENABLE_KAGGLE_DATASETS: "true"
    ports:
      - "${EXTERNAL_PORT:-8888}:8888"
    volumes:
      - ./:/app
    env_file:
      - ./jupyter-config/.env
    restart: unless-stopped
    profiles: ["local-kaggle-datasets"]